### ISSUE TITLE
Build fails with ninja

### ISSUE THREAD

**Issue by sodface** [tari01/odio-edit#5] opened 2024-09-04 02:42 UTC
Hi, the Alpine package has been using ninja to build odio-edit and it broke with this release, complaining:

> ninja: multiple rules generate data/odio-edit.desktop

I spent some time trying to figure out what was going on with ninja but failed. I switched to make and then it started building ok. My [upgrade MR is here](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/71385), I'm not sure if the Alpine devs will have an issue with ignoring the ninja failure and moving to make.

So this isn't really a bug report per se, just letting you know.

**Comment by tari01** [comment] 2024-09-04 05:28
The issue here is that **Ninja** and `intltool_merge_translations` in the [cmake-extras](https://gitlab.com/ubports/development/core/cmake-extras/-/blob/main/src/Intltool/IntltoolConfig.cmake?ref_type=heads#L368) package don't play nice.

https://github.com/tari01/odio-edit/blob/3c397bf139905908829afb669d835ff58d23e8d3/data/CMakeLists.txt#L10

There was a mention of this some time ago, but it was never fixed properly:

https://github.com/AyatanaIndicators/libayatana-common/issues/60#issuecomment-1253545854

I'm sorry, but I don't have the time to research this right now. It would be nice if somebody could look into `intltool_merge_translations` and come up with a fix.

**Comment by sodface** [comment] 2024-09-04 11:35
Yes, sorry, I didn't provide much detail in my first post. I did narrow it down to `intltool_merge_translations` and by just removing that line the ninja build would work. Looking at a diff of  "good" and bad `build.ninja` files I could see that extra targets for `data/odio-edit.desktop` had been generated but that was as far as I got before trying make.

My Alpine MR was merged so this isn't a packing issue for me at the moment. I will try to look at the issue again when I get some free time.

Do you want to keep this issue open?

**Comment by tari01** [comment] 2024-09-04 14:27
I think you can close this, the issue is in `cmake-extras`, so the fix should eventually come from there.

**Closed** 2024-09-04 14:35 UTC
